/**
 * Auto-generates Luau behavior scripts from canvas element GameLogicProperties.
 * Each behavior type generates one script (not per-instance) using CollectionService tags.
 */

import type { CanvasElement } from "../stores/canvasStore";
import type { GameLogicProperties } from "./gameLogic";

interface GeneratedScript {
  path: string;
  content: string;
}

export function generateAllBehaviorScripts(
  elements: CanvasElement[],
  template: string,
): GeneratedScript[] {
  const scripts: GeneratedScript[] = [];

  // Group elements by behavior type
  const hasEnemies = elements.some((e) => e.category === "character" && (e.type === "enemy" || e.type === "boss"));
  const hasShops = elements.some((e) => e.type === "shopkeeper" || e.type === "shop");
  const hasCollectibles = elements.some((e) => e.type === "coin" || e.type === "gem");
  const hasMovingPlatforms = elements.some((e) => e.type === "moving-platform" || e.logic?.moveSpeed);
  const hasDisappearing = elements.some((e) => e.type === "disappearing");
  const hasBouncy = elements.some((e) => e.type === "bouncy");
  const hasConveyors = elements.some((e) => e.type === "conveyor" || e.type === "conveyor-belt");
  const hasKillBricks = elements.some((e) => e.type === "killbrick" || e.type === "lava" || e.type === "spikes" || e.logic?.killOnTouch);
  const hasSpinners = elements.some((e) => e.type === "spinner");
  const hasClickOrbs = elements.some((e) => e.type === "click-orb");
  const hasPrestigePads = elements.some((e) => e.type === "prestige-pad");

  if (hasEnemies) {
    const enemies = elements.filter((e) => e.category === "character" && (e.type === "enemy" || e.type === "boss"));
    scripts.push({
      path: "src/server/EnemyBehavior.server.luau",
      content: generateEnemyScript(enemies[0]?.logic || {}, template),
    });
  }

  if (hasShops) {
    const shops = elements.filter((e) => e.type === "shopkeeper" || e.type === "shop");
    scripts.push({
      path: "src/server/ShopSystem.server.luau",
      content: generateShopScript(shops[0]?.logic || {}),
    });
  }

  if (hasCollectibles) {
    const coins = elements.filter((e) => e.type === "coin" || e.type === "gem");
    scripts.push({
      path: "src/server/CollectibleSystem.server.luau",
      content: generateCollectibleScript(coins[0]?.logic || {}),
    });
  }

  if (hasMovingPlatforms || hasDisappearing || hasBouncy || hasConveyors) {
    scripts.push({
      path: "src/server/PlatformBehaviors.server.luau",
      content: generatePlatformBehaviorScript(
        hasMovingPlatforms,
        hasDisappearing,
        hasBouncy,
        hasConveyors,
        elements.find((e) => e.type === "moving-platform")?.logic || {},
      ),
    });
  }

  if (hasKillBricks || hasSpinners) {
    scripts.push({
      path: "src/server/HazardSystem.server.luau",
      content: generateHazardScript(hasKillBricks, hasSpinners),
    });
  }

  if (hasClickOrbs) {
    scripts.push({
      path: "src/server/ClickOrbHandler.server.luau",
      content: generateClickOrbScript(),
    });
  }

  if (hasPrestigePads) {
    scripts.push({
      path: "src/server/PrestigeHandler.server.luau",
      content: generatePrestigeScript(),
    });
  }

  return scripts;
}

function generateEnemyScript(logic: GameLogicProperties, _template: string): string {
  const hp = logic.health || 100;
  const dmg = logic.damage || 10;
  const speed = logic.walkSpeed || 12;
  const respawn = logic.respawnTime || 10;
  const range = logic.attackRange || 15;
  const behavior = logic.aiBehavior || "chase";

  return `-- EnemyBehavior: auto-generated by RobloxForge
-- Handles enemy AI, combat, and drops using CollectionService tags
local CollectionService = game:GetService("CollectionService")
local Players = game:GetService("Players")

local ENEMY_CONFIG = {
\thealth = ${hp},
\tdamage = ${dmg},
\twalkSpeed = ${speed},
\trespawnTime = ${respawn},
\tattackRange = ${range},
\tbehavior = "${behavior}",
}

local function setupEnemy(enemyModel)
\tlocal humanoid = enemyModel:FindFirstChildOfClass("Humanoid")
\tif not humanoid then
\t\thumanoid = Instance.new("Humanoid")
\t\thumanoid.Parent = enemyModel
\tend

\thumanoid.MaxHealth = ENEMY_CONFIG.health
\thumanoid.Health = ENEMY_CONFIG.health
\thumanoid.WalkSpeed = ENEMY_CONFIG.walkSpeed

\t-- Simple AI loop
\ttask.spawn(function()
\t\twhile humanoid and humanoid.Health > 0 do
\t\t\tlocal closest = nil
\t\t\tlocal closestDist = ENEMY_CONFIG.attackRange

\t\t\tfor _, player in Players:GetPlayers() do
\t\t\t\tlocal char = player.Character
\t\t\t\tif char and char:FindFirstChild("HumanoidRootPart") and enemyModel:FindFirstChild("HumanoidRootPart") then
\t\t\t\t\tlocal dist = (char.HumanoidRootPart.Position - enemyModel.HumanoidRootPart.Position).Magnitude
\t\t\t\t\tif dist < closestDist then
\t\t\t\t\t\tclosest = char
\t\t\t\t\t\tclosestDist = dist
\t\t\t\t\tend
\t\t\t\tend
\t\t\tend

\t\t\tif closest and ENEMY_CONFIG.behavior == "chase" then
\t\t\t\thumanoid:MoveTo(closest.HumanoidRootPart.Position)
\t\t\t\t-- Deal damage on close range
\t\t\t\tif closestDist < 5 then
\t\t\t\t\tlocal targetHumanoid = closest:FindFirstChild("Humanoid")
\t\t\t\t\tif targetHumanoid then
\t\t\t\t\t\ttargetHumanoid:TakeDamage(ENEMY_CONFIG.damage)
\t\t\t\t\tend
\t\t\t\tend
\t\t\tend

\t\t\ttask.wait(0.5)
\t\tend
\tend)

\t-- Respawn on death
\thumanoid.Died:Connect(function()
\t\ttask.wait(ENEMY_CONFIG.respawnTime)
\t\tif enemyModel and enemyModel.Parent then
\t\t\thumanoid.Health = humanoid.MaxHealth
\t\tend
\tend)
end

-- Setup all tagged enemies
for _, enemy in CollectionService:GetTagged("Enemy") do
\tsetupEnemy(enemy)
end

CollectionService:GetInstanceAddedSignal("Enemy"):Connect(setupEnemy)

print("EnemyBehavior loaded")
`;
}

function generateShopScript(logic: GameLogicProperties): string {
  const items = logic.shopItems || [
    { name: "Speed Boost", price: 50, currency: "Coins", icon: "speed", description: "Run faster" },
    { name: "Double Jump", price: 100, currency: "Coins", icon: "jump", description: "Jump twice" },
  ];
  const shopName = logic.shopName || "Shop";

  return `-- ShopSystem: auto-generated by RobloxForge
-- Handles NPC shop interactions via ProximityPrompt
local CollectionService = game:GetService("CollectionService")
local Players = game:GetService("Players")

local SHOP_ITEMS = {
${items.map((item) => `\t{ name = "${item.name}", price = ${item.price}, currency = "${item.currency}" },`).join("\n")}
}

local function setupShop(shopPart)
\tlocal prompt = shopPart:FindFirstChildOfClass("ProximityPrompt")
\tif not prompt then
\t\tprompt = Instance.new("ProximityPrompt")
\t\tprompt.ActionText = "Shop"
\t\tprompt.ObjectText = "${shopName}"
\t\tprompt.MaxActivationDistance = 8
\t\tprompt.HoldDuration = 0
\t\tprompt.Parent = shopPart
\tend

\tprompt.Triggered:Connect(function(player)
\t\t-- Fire remote to open shop UI on client
\t\tlocal remote = game.ReplicatedStorage:FindFirstChild("OpenShop")
\t\tif not remote then
\t\t\tremote = Instance.new("RemoteEvent")
\t\t\tremote.Name = "OpenShop"
\t\t\tremote.Parent = game.ReplicatedStorage
\t\tend
\t\tremote:FireClient(player, SHOP_ITEMS)
\tend)
end

for _, shop in CollectionService:GetTagged("Shopkeeper") do
\tsetupShop(shop)
end

CollectionService:GetInstanceAddedSignal("Shopkeeper"):Connect(setupShop)

print("ShopSystem loaded")
`;
}

function generateCollectibleScript(logic: GameLogicProperties): string {
  const value = logic.value || 1;
  const currency = logic.currency || "Coins";
  const respawnTime = logic.collectRespawnTime || 5;

  return `-- CollectibleSystem: auto-generated by RobloxForge
-- Handles coin/gem collection with respawn
local CollectionService = game:GetService("CollectionService")
local Players = game:GetService("Players")

local COLLECT_CONFIG = {
\tvalue = ${value},
\tcurrency = "${currency}",
\trespawnTime = ${respawnTime},
}

local debounce = {}

local function setupCollectible(part)
\tpart.Touched:Connect(function(hit)
\t\tlocal player = Players:GetPlayerFromCharacter(hit.Parent)
\t\tif not player then return end
\t\tif debounce[part] then return end
\t\tdebounce[part] = true

\t\t-- Give currency
\t\tlocal leaderstats = player:FindFirstChild("leaderstats")
\t\tif leaderstats then
\t\t\tlocal currStat = leaderstats:FindFirstChild(COLLECT_CONFIG.currency)
\t\t\tif currStat then
\t\t\t\tcurrStat.Value += COLLECT_CONFIG.value
\t\t\tend
\t\tend

\t\t-- Hide and respawn
\t\tpart.Transparency = 1
\t\tpart.CanCollide = false

\t\ttask.delay(COLLECT_CONFIG.respawnTime, function()
\t\t\tpart.Transparency = 0
\t\t\tpart.CanCollide = true
\t\t\tdebounce[part] = nil
\t\tend)
\tend)
end

for _, coin in CollectionService:GetTagged("Collectible") do
\tsetupCollectible(coin)
end

CollectionService:GetInstanceAddedSignal("Collectible"):Connect(setupCollectible)

print("CollectibleSystem loaded")
`;
}

function generatePlatformBehaviorScript(
  hasMoving: boolean,
  hasDisappearing: boolean,
  hasBouncy: boolean,
  hasConveyors: boolean,
  logic: GameLogicProperties,
): string {
  const moveSpeed = logic.moveSpeed || 4;
  const moveDistance = logic.moveDistance || 10;

  const sections: string[] = [
    `-- PlatformBehaviors: auto-generated by RobloxForge`,
    `local CollectionService = game:GetService("CollectionService")`,
    `local TweenService = game:GetService("TweenService")`,
    ``,
  ];

  if (hasMoving) {
    sections.push(`-- Moving Platforms`);
    sections.push(`for _, platform in CollectionService:GetTagged("MovingPlatform") do`);
    sections.push(`\tlocal startPos = platform.Position`);
    sections.push(`\tlocal distance = platform:GetAttribute("MoveDistance") or ${moveDistance}`);
    sections.push(`\tlocal speed = platform:GetAttribute("MoveSpeed") or ${moveSpeed}`);
    sections.push(`\tlocal dir = platform:GetAttribute("MoveDirection") or "vertical"`);
    sections.push(`\tlocal offset = dir == "vertical" and Vector3.new(0, distance, 0) or Vector3.new(distance, 0, 0)`);
    sections.push(`\tlocal endPos = startPos + offset`);
    sections.push(`\tlocal duration = distance / speed`);
    sections.push(``);
    sections.push(`\ttask.spawn(function()`);
    sections.push(`\t\twhile platform and platform.Parent do`);
    sections.push(`\t\t\tlocal tweenUp = TweenService:Create(platform, TweenInfo.new(duration, Enum.EasingStyle.Linear), { Position = endPos })`);
    sections.push(`\t\t\ttweenUp:Play()`);
    sections.push(`\t\t\ttweenUp.Completed:Wait()`);
    sections.push(`\t\t\tlocal tweenDown = TweenService:Create(platform, TweenInfo.new(duration, Enum.EasingStyle.Linear), { Position = startPos })`);
    sections.push(`\t\t\ttweenDown:Play()`);
    sections.push(`\t\t\ttweenDown.Completed:Wait()`);
    sections.push(`\t\tend`);
    sections.push(`\tend)`);
    sections.push(`end`);
    sections.push(``);
  }

  if (hasDisappearing) {
    sections.push(`-- Disappearing Platforms`);
    sections.push(`for _, platform in CollectionService:GetTagged("DisappearingPlatform") do`);
    sections.push(`\tlocal disappearDelay = platform:GetAttribute("DisappearDelay") or 1`);
    sections.push(`\tlocal reappearDelay = platform:GetAttribute("ReappearDelay") or 3`);
    sections.push(``);
    sections.push(`\tplatform.Touched:Connect(function(hit)`);
    sections.push(`\t\tif not hit.Parent:FindFirstChild("Humanoid") then return end`);
    sections.push(`\t\ttask.wait(disappearDelay)`);
    sections.push(`\t\tplatform.Transparency = 1`);
    sections.push(`\t\tplatform.CanCollide = false`);
    sections.push(`\t\ttask.wait(reappearDelay)`);
    sections.push(`\t\tplatform.Transparency = 0`);
    sections.push(`\t\tplatform.CanCollide = true`);
    sections.push(`\tend)`);
    sections.push(`end`);
    sections.push(``);
  }

  if (hasBouncy) {
    sections.push(`-- Bouncy Platforms`);
    sections.push(`local Players = game:GetService("Players")`);
    sections.push(`for _, platform in CollectionService:GetTagged("BouncyPlatform") do`);
    sections.push(`\tlocal bounceForce = platform:GetAttribute("BounceForce") or 80`);
    sections.push(``);
    sections.push(`\tplatform.Touched:Connect(function(hit)`);
    sections.push(`\t\tlocal player = Players:GetPlayerFromCharacter(hit.Parent)`);
    sections.push(`\t\tif not player then return end`);
    sections.push(`\t\tlocal hrp = hit.Parent:FindFirstChild("HumanoidRootPart")`);
    sections.push(`\t\tif hrp then`);
    sections.push(`\t\t\thrp.AssemblyLinearVelocity = Vector3.new(hrp.AssemblyLinearVelocity.X, bounceForce, hrp.AssemblyLinearVelocity.Z)`);
    sections.push(`\t\tend`);
    sections.push(`\tend)`);
    sections.push(`end`);
    sections.push(``);
  }

  if (hasConveyors) {
    sections.push(`-- Conveyor Belts`);
    sections.push(`for _, belt in CollectionService:GetTagged("Conveyor") do`);
    sections.push(`\tlocal speed = belt:GetAttribute("ConveyorSpeed") or 8`);
    sections.push(`\tlocal dir = belt:GetAttribute("ConveyorDirection") or "right"`);
    sections.push(`\tlocal velocity = dir == "right" and Vector3.new(speed, 0, 0) or Vector3.new(-speed, 0, 0)`);
    sections.push(``);
    sections.push(`\tlocal att = Instance.new("Attachment")`);
    sections.push(`\tatt.Parent = belt`);
    sections.push(`\tlocal force = Instance.new("LinearVelocity")`);
    sections.push(`\tforce.MaxForce = 1000`);
    sections.push(`\tforce.VelocityConstraintMode = Enum.VelocityConstraintMode.Plane`);
    sections.push(`\tforce.PrimaryTangentAxis = velocity.Unit`);
    sections.push(`\tforce.PlaneVelocity = Vector2.new(speed, 0)`);
    sections.push(`\tforce.Attachment0 = att`);
    sections.push(`\tforce.Parent = belt`);
    sections.push(`end`);
    sections.push(``);
  }

  sections.push(`print("PlatformBehaviors loaded")`);
  sections.push(``);

  return sections.join("\n");
}

function generateHazardScript(hasKill: boolean, hasSpinners: boolean): string {
  const sections: string[] = [
    `-- HazardSystem: auto-generated by RobloxForge`,
    `local CollectionService = game:GetService("CollectionService")`,
    `local Players = game:GetService("Players")`,
    ``,
  ];

  if (hasKill) {
    sections.push(`-- Kill Bricks (instant death on touch)`);
    sections.push(`for _, brick in CollectionService:GetTagged("KillBrick") do`);
    sections.push(`\tbrick.Touched:Connect(function(hit)`);
    sections.push(`\t\tlocal player = Players:GetPlayerFromCharacter(hit.Parent)`);
    sections.push(`\t\tif not player then return end`);
    sections.push(`\t\tlocal humanoid = hit.Parent:FindFirstChild("Humanoid")`);
    sections.push(`\t\tif humanoid then humanoid.Health = 0 end`);
    sections.push(`\tend)`);
    sections.push(`end`);
    sections.push(``);
  }

  if (hasSpinners) {
    sections.push(`-- Spinners (rotating hazards)`);
    sections.push(`local RunService = game:GetService("RunService")`);
    sections.push(`for _, spinner in CollectionService:GetTagged("Spinner") do`);
    sections.push(`\tlocal speed = spinner:GetAttribute("SpinSpeed") or 2`);
    sections.push(`\tRunService.Heartbeat:Connect(function(dt)`);
    sections.push(`\t\tspinner.CFrame = spinner.CFrame * CFrame.Angles(0, speed * dt, 0)`);
    sections.push(`\tend)`);
    sections.push(`\tspinner.Touched:Connect(function(hit)`);
    sections.push(`\t\tlocal humanoid = hit.Parent and hit.Parent:FindFirstChild("Humanoid")`);
    sections.push(`\t\tif humanoid then humanoid.Health = 0 end`);
    sections.push(`\tend)`);
    sections.push(`end`);
    sections.push(``);
  }

  sections.push(`print("HazardSystem loaded")`);
  sections.push(``);

  return sections.join("\n");
}

function generateClickOrbScript(): string {
  return `-- ClickOrbHandler: auto-generated by RobloxForge
-- Makes tagged ClickOrb parts clickable for currency
local CollectionService = game:GetService("CollectionService")
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local clickEvent = ReplicatedStorage:FindFirstChild("Click") or Instance.new("RemoteEvent")
clickEvent.Name = "Click"
clickEvent.Parent = ReplicatedStorage

for _, orb in CollectionService:GetTagged("ClickOrb") do
\tlocal detector = orb:FindFirstChildOfClass("ClickDetector") or Instance.new("ClickDetector")
\tdetector.MaxActivationDistance = 15
\tdetector.Parent = orb

\tdetector.MouseClick:Connect(function(player)
\t\tclickEvent:FireServer()
\tend)
end

CollectionService:GetInstanceAddedSignal("ClickOrb"):Connect(function(orb)
\tlocal detector = Instance.new("ClickDetector")
\tdetector.MaxActivationDistance = 15
\tdetector.Parent = orb
\tdetector.MouseClick:Connect(function()
\t\tclickEvent:FireServer()
\tend)
end)

print("ClickOrbHandler loaded")
`;
}

function generatePrestigeScript(): string {
  return `-- PrestigeHandler: auto-generated by RobloxForge
-- Makes tagged PrestigePad parts trigger prestige on touch
local CollectionService = game:GetService("CollectionService")
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local prestigeEvent = ReplicatedStorage:FindFirstChild("Prestige") or Instance.new("RemoteEvent")
prestigeEvent.Name = "Prestige"
prestigeEvent.Parent = ReplicatedStorage

local debounce = {}

for _, pad in CollectionService:GetTagged("PrestigePad") do
\tlocal layer = pad:GetAttribute("PrestigeLayer") or 1

\tpad.Touched:Connect(function(hit)
\t\tlocal player = Players:GetPlayerFromCharacter(hit.Parent)
\t\tif not player then return end
\t\tif debounce[player] then return end
\t\tdebounce[player] = true

\t\tprestigeEvent:FireServer(layer)

\t\ttask.delay(2, function()
\t\t\tdebounce[player] = nil
\t\tend)
\tend)
end

print("PrestigeHandler loaded")
`;
}
