/**
 * Compiles a visual script node graph into a Luau server script.
 * Uses topological sorting to determine execution order and
 * generates idiomatic Roblox Luau code from node connections.
 */

import { NODE_TYPES } from "./nodeTypes";
import type { Node, Edge } from "@xyflow/react";

interface NodeData {
  nodeType: string;
  values: Record<string, string | number | boolean>;
}

/**
 * Compile a node graph to a Luau server script string.
 */
export function compileGraphToLuau(
  nodes: Node<NodeData>[],
  edges: Edge[],
  scriptName: string,
): string {
  const lines: string[] = [
    `-- ${scriptName}: auto-generated by RobloxForge Visual Scripting`,
    "-- Edit freely — changes won't be overwritten unless you recompile",
    "",
  ];

  // Collect which services are needed
  const services = new Set<string>();
  const triggerNodes = nodes.filter(
    (n) => NODE_TYPES[n.data.nodeType]?.category === "trigger",
  );

  for (const node of triggerNodes) {
    const t = node.data.nodeType;
    if (t === "on_touched") {
      services.add("CollectionService");
      services.add("Players");
    }
    if (t === "on_player_join" || t === "on_died" || t === "on_player_leave") {
      services.add("Players");
    }
    if (t === "on_chat") {
      services.add("Players");
    }
  }

  // Check which services are needed by action nodes
  const hasMove = nodes.some((n) => n.data.nodeType === "move_object");
  if (hasMove) services.add("TweenService");

  const hasHint = nodes.some((n) => n.data.nodeType === "show_hint");
  if (hasHint) services.add("Players");

  const hasSetColor = nodes.some((n) => n.data.nodeType === "set_part_color");
  if (hasSetColor) services.add("CollectionService");

  // Emit service requires
  for (const svc of services) {
    lines.push(`local ${svc} = game:GetService("${svc}")`);
  }
  if (services.size > 0) lines.push("");

  // Build adjacency: for each node, find what signal edges connect to it
  const signalEdges = edges.filter((e) => {
    // Signal edges connect signal outputs to signal inputs
    return true; // All edges in our system are signal/data flow
  });

  // For each trigger, generate a handler block
  for (const trigger of triggerNodes) {
    const chain = getSignalChain(trigger.id, nodes, signalEdges);
    lines.push(...generateTriggerBlock(trigger, chain, nodes, edges));
    lines.push("");
  }

  lines.push(`print("${scriptName} loaded")`);
  lines.push("");

  return lines.join("\n");
}

/** Follow signal edges from a trigger through the action chain. */
function getSignalChain(
  startId: string,
  nodes: Node<NodeData>[],
  edges: Edge[],
): Node<NodeData>[] {
  const chain: Node<NodeData>[] = [];
  const visited = new Set<string>();
  let currentId = startId;

  while (currentId) {
    if (visited.has(currentId)) break;
    visited.add(currentId);

    // Find signal edge from current node's signal output
    const outEdge = edges.find(
      (e) =>
        e.source === currentId &&
        (e.sourceHandle === "signal" ||
          e.sourceHandle === "true" ||
          e.sourceHandle === "Then" ||
          !e.sourceHandle),
    );

    if (!outEdge) break;

    const nextNode = nodes.find((n) => n.id === outEdge.target);
    if (!nextNode) break;

    chain.push(nextNode);
    currentId = nextNode.id;
  }

  return chain;
}

/** Get the value for a node input — either from a connected edge or the default. */
function getInputValue(
  nodeId: string,
  inputId: string,
  nodes: Node<NodeData>[],
  edges: Edge[],
): string {
  const node = nodes.find((n) => n.id === nodeId);
  if (!node) return "nil";

  // Check if there's a data edge connecting to this input
  const dataEdge = edges.find(
    (e) => e.target === nodeId && e.targetHandle === inputId,
  );

  if (dataEdge) {
    // Return a variable reference from the source node
    return `_${dataEdge.source}_${dataEdge.sourceHandle}`;
  }

  // Use the node's configured value or the default
  const val = node.data.values?.[inputId];
  if (val !== undefined) {
    if (typeof val === "string") return `"${val}"`;
    return String(val);
  }

  const typeDef = NODE_TYPES[node.data.nodeType];
  const portDef = typeDef?.inputs.find((p) => p.id === inputId);
  if (portDef?.defaultValue !== undefined) {
    if (typeof portDef.defaultValue === "string")
      return `"${portDef.defaultValue}"`;
    return String(portDef.defaultValue);
  }

  return "nil";
}

/** Generate Luau code for a trigger node and its connected action chain. */
function generateTriggerBlock(
  trigger: Node<NodeData>,
  chain: Node<NodeData>[],
  allNodes: Node<NodeData>[],
  allEdges: Edge[],
): string[] {
  const lines: string[] = [];
  const t = trigger.data.nodeType;

  if (t === "on_touched") {
    const tag = getInputValue(trigger.id, "tag", allNodes, allEdges);
    lines.push(`-- On Touched: parts tagged ${tag}`);
    lines.push(`for _, part in CollectionService:GetTagged(${tag}) do`);
    lines.push(`\tpart.Touched:Connect(function(hit)`);
    lines.push(`\t\tlocal player = Players:GetPlayerFromCharacter(hit.Parent)`);
    lines.push(`\t\tif not player then return end`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend)`);
    lines.push(`end`);
  } else if (t === "on_timer") {
    const interval = getInputValue(trigger.id, "interval", allNodes, allEdges);
    lines.push(`-- Timer: every ${interval} seconds`);
    lines.push(`task.spawn(function()`);
    lines.push(`\twhile true do`);
    lines.push(`\t\ttask.wait(${interval})`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend`);
    lines.push(`end)`);
  } else if (t === "on_player_join") {
    lines.push(`-- On Player Join`);
    lines.push(`Players.PlayerAdded:Connect(function(player)`);
    lines.push(...indentChain(chain, allNodes, allEdges, 1));
    lines.push(`end)`);
  } else if (t === "on_died") {
    lines.push(`-- On Player Died`);
    lines.push(`Players.PlayerAdded:Connect(function(player)`);
    lines.push(`\tplayer.CharacterAdded:Connect(function(character)`);
    lines.push(`\t\tlocal humanoid = character:WaitForChild("Humanoid")`);
    lines.push(`\t\thumanoid.Died:Connect(function()`);
    lines.push(...indentChain(chain, allNodes, allEdges, 3));
    lines.push(`\t\tend)`);
    lines.push(`\tend)`);
    lines.push(`end)`);
  } else if (t === "on_player_leave") {
    lines.push(`-- On Player Leave`);
    lines.push(`Players.PlayerRemoving:Connect(function(player)`);
    lines.push(...indentChain(chain, allNodes, allEdges, 1));
    lines.push(`end)`);
  } else if (t === "on_chat") {
    const keyword = getInputValue(trigger.id, "keyword", allNodes, allEdges);
    lines.push(`-- On Chat${keyword !== '""' ? ` (keyword: ${keyword})` : ""}`);
    lines.push(`Players.PlayerAdded:Connect(function(player)`);
    lines.push(`\tplayer.Chatted:Connect(function(message)`);
    if (keyword !== '""') {
      lines.push(`\t\tif not string.find(string.lower(message), string.lower(${keyword})) then return end`);
    }
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend)`);
    lines.push(`end)`);
  }

  return lines;
}

/** Generate code for a chain of action/logic nodes at a given indent level. */
function indentChain(
  chain: Node<NodeData>[],
  allNodes: Node<NodeData>[],
  allEdges: Edge[],
  indent: number,
): string[] {
  const lines: string[] = [];
  const tabs = "\t".repeat(indent);

  for (const node of chain) {
    const t = node.data.nodeType;

    if (t === "take_damage") {
      const amount = getInputValue(node.id, "amount", allNodes, allEdges);
      lines.push(`${tabs}-- Take Damage`);
      lines.push(`${tabs}local character = player.Character`);
      lines.push(`${tabs}if character then`);
      lines.push(`${tabs}\tlocal humanoid = character:FindFirstChild("Humanoid")`);
      lines.push(`${tabs}\tif humanoid then`);
      lines.push(`${tabs}\t\thumanoid:TakeDamage(${amount})`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
    } else if (t === "move_object") {
      const direction = getInputValue(node.id, "direction", allNodes, allEdges);
      const distance = getInputValue(node.id, "distance", allNodes, allEdges);
      lines.push(`${tabs}-- Move Object`);
      lines.push(`${tabs}local moveDir = Vector3.new(0, ${direction === '"up"' ? distance : "0"}, ${direction === '"forward"' ? distance : "0"})`);
      lines.push(`${tabs}local goal = { CFrame = part.CFrame + moveDir }`);
      lines.push(`${tabs}local tween = TweenService:Create(part, TweenInfo.new(1), goal)`);
      lines.push(`${tabs}tween:Play()`);
    } else if (t === "play_sound") {
      const soundId = getInputValue(node.id, "soundId", allNodes, allEdges);
      lines.push(`${tabs}-- Play Sound`);
      lines.push(`${tabs}local sound = Instance.new("Sound")`);
      lines.push(`${tabs}sound.SoundId = ${soundId}`);
      lines.push(`${tabs}sound.Parent = workspace`);
      lines.push(`${tabs}sound:Play()`);
      lines.push(`${tabs}sound.Ended:Once(function() sound:Destroy() end)`);
    } else if (t === "print_message") {
      const message = getInputValue(node.id, "message", allNodes, allEdges);
      lines.push(`${tabs}print(${message})`);
    } else if (t === "heal_player") {
      const amount = getInputValue(node.id, "amount", allNodes, allEdges);
      lines.push(`${tabs}-- Heal Player`);
      lines.push(`${tabs}local character = player and player.Character`);
      lines.push(`${tabs}if character then`);
      lines.push(`${tabs}\tlocal humanoid = character:FindFirstChild("Humanoid")`);
      lines.push(`${tabs}\tif humanoid then`);
      lines.push(`${tabs}\t\thumanoid.Health = math.min(humanoid.Health + ${amount}, humanoid.MaxHealth)`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
    } else if (t === "kill_player") {
      lines.push(`${tabs}-- Kill Player`);
      lines.push(`${tabs}local character = player and player.Character`);
      lines.push(`${tabs}if character then`);
      lines.push(`${tabs}\tlocal humanoid = character:FindFirstChild("Humanoid")`);
      lines.push(`${tabs}\tif humanoid then humanoid.Health = 0 end`);
      lines.push(`${tabs}end`);
    } else if (t === "respawn_player") {
      lines.push(`${tabs}-- Respawn Player`);
      lines.push(`${tabs}if player then player:LoadCharacter() end`);
    } else if (t === "teleport_player") {
      const x = getInputValue(node.id, "x", allNodes, allEdges);
      const y = getInputValue(node.id, "y", allNodes, allEdges);
      const z = getInputValue(node.id, "z", allNodes, allEdges);
      lines.push(`${tabs}-- Teleport Player`);
      lines.push(`${tabs}local character = player and player.Character`);
      lines.push(`${tabs}if character then`);
      lines.push(`${tabs}\tcharacter:PivotTo(CFrame.new(${x}, ${y}, ${z}))`);
      lines.push(`${tabs}end`);
    } else if (t === "set_part_color") {
      const tag = getInputValue(node.id, "tag", allNodes, allEdges);
      const color = getInputValue(node.id, "color", allNodes, allEdges);
      lines.push(`${tabs}-- Set Part Color`);
      lines.push(`${tabs}for _, colorPart in CollectionService:GetTagged(${tag}) do`);
      lines.push(`${tabs}\tcolorPart.BrickColor = BrickColor.new(${color})`);
      lines.push(`${tabs}end`);
    } else if (t === "show_hint") {
      const message = getInputValue(node.id, "message", allNodes, allEdges);
      const duration = getInputValue(node.id, "duration", allNodes, allEdges);
      lines.push(`${tabs}-- Show Hint`);
      lines.push(`${tabs}local hint = Instance.new("Hint")`);
      lines.push(`${tabs}hint.Text = ${message}`);
      lines.push(`${tabs}hint.Parent = workspace`);
      lines.push(`${tabs}task.delay(${duration}, function() hint:Destroy() end)`);
    } else if (t === "give_points") {
      const amount = getInputValue(node.id, "amount", allNodes, allEdges);
      const stat = getInputValue(node.id, "stat", allNodes, allEdges);
      lines.push(`${tabs}-- Give Points`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal leaderstats = player:FindFirstChild("leaderstats")`);
      lines.push(`${tabs}\tif leaderstats then`);
      lines.push(`${tabs}\t\tlocal statValue = leaderstats:FindFirstChild(${stat})`);
      lines.push(`${tabs}\t\tif statValue then statValue.Value += ${amount} end`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
    } else if (t === "wait_delay") {
      const seconds = getInputValue(node.id, "seconds", allNodes, allEdges);
      lines.push(`${tabs}task.wait(${seconds})`);
    } else if (t === "random_number") {
      const min = getInputValue(node.id, "min", allNodes, allEdges);
      const max = getInputValue(node.id, "max", allNodes, allEdges);
      const varName = `_${node.id.replace(/[^a-z0-9]/gi, "_")}_value`;
      lines.push(`${tabs}-- Random Number`);
      lines.push(`${tabs}local ${varName} = math.random(${min}, ${max})`);
    } else if (t === "compare") {
      const a = getInputValue(node.id, "a", allNodes, allEdges);
      const op = getInputValue(node.id, "operator", allNodes, allEdges);
      const b = getInputValue(node.id, "b", allNodes, allEdges);
      // Find true/false branches
      const trueBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "true",
      );
      const falseBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "false",
      );
      lines.push(`${tabs}-- Compare`);
      lines.push(`${tabs}if ${a} ${op.replace(/^"|"$/g, "")} ${b} then`);
      if (trueBranch) {
        const trueNode = allNodes.find((n) => n.id === trueBranch.target);
        if (trueNode) {
          lines.push(...indentChain([trueNode], allNodes, allEdges, indent + 1));
        }
      }
      if (falseBranch) {
        lines.push(`${tabs}else`);
        const falseNode = allNodes.find((n) => n.id === falseBranch.target);
        if (falseNode) {
          lines.push(...indentChain([falseNode], allNodes, allEdges, indent + 1));
        }
      }
      lines.push(`${tabs}end`);
    } else if (t === "if_else") {
      const condition = getInputValue(node.id, "condition", allNodes, allEdges);
      // Find true/false branches
      const trueBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "true",
      );
      const falseBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "false",
      );
      lines.push(`${tabs}if ${condition} then`);
      if (trueBranch) {
        const trueNode = allNodes.find((n) => n.id === trueBranch.target);
        if (trueNode) {
          const trueChain = [trueNode];
          lines.push(...indentChain(trueChain, allNodes, allEdges, indent + 1));
        }
      }
      if (falseBranch) {
        lines.push(`${tabs}else`);
        const falseNode = allNodes.find((n) => n.id === falseBranch.target);
        if (falseNode) {
          const falseChain = [falseNode];
          lines.push(...indentChain(falseChain, allNodes, allEdges, indent + 1));
        }
      }
      lines.push(`${tabs}end`);
    }
  }

  return lines;
}
