/**
 * Compiles a visual script node graph into a Luau server script.
 * Uses topological sorting to determine execution order and
 * generates idiomatic Roblox Luau code from node connections.
 */

import { NODE_TYPES } from "./nodeTypes";
import type { Node, Edge } from "@xyflow/react";

interface NodeData {
  nodeType: string;
  values: Record<string, string | number | boolean>;
}

/**
 * Compile a node graph to a Luau server script string.
 */
export function compileGraphToLuau(
  nodes: Node<NodeData>[],
  edges: Edge[],
  scriptName: string,
): string {
  const lines: string[] = [
    `-- ${scriptName}: auto-generated by RobloxForge Visual Scripting`,
    "-- Edit freely — changes won't be overwritten unless you recompile",
    "",
  ];

  // Collect which services are needed
  const services = new Set<string>();
  const triggerNodes = nodes.filter(
    (n) => NODE_TYPES[n.data.nodeType]?.category === "trigger",
  );

  for (const node of triggerNodes) {
    const t = node.data.nodeType;
    if (t === "on_touched" || t === "on_proximity" || t === "on_click") {
      services.add("CollectionService");
      services.add("Players");
    }
    if (t === "on_player_join" || t === "on_died" || t === "on_player_leave") {
      services.add("Players");
    }
    if (t === "on_chat") {
      services.add("Players");
    }
    if (t === "on_gamepass_purchased" || t === "on_developer_product") {
      services.add("MarketplaceService");
      services.add("Players");
    }
  }

  // Check which services are needed by action nodes
  const allTypes = new Set(nodes.map((n) => n.data.nodeType));

  if (allTypes.has("move_object") || allTypes.has("tween_property")) services.add("TweenService");
  if (allTypes.has("show_hint") || allTypes.has("show_notification") || allTypes.has("for_each_player")) services.add("Players");
  if (allTypes.has("set_part_color") || allTypes.has("create_particle")) services.add("CollectionService");
  if (allTypes.has("save_data") || allTypes.has("load_data")) services.add("DataStoreService");
  if (allTypes.has("prompt_purchase") || allTypes.has("prompt_gamepass") || allTypes.has("check_gamepass")) services.add("MarketplaceService");
  if (allTypes.has("change_lighting")) services.add("Lighting");
  if (allTypes.has("screen_shake") || allTypes.has("fire_remote") || allTypes.has("fire_server")) services.add("ReplicatedStorage");

  // Emit service requires
  for (const svc of services) {
    if (svc === "Lighting") {
      lines.push(`local ${svc} = game:GetService("${svc}")`);
    } else {
      lines.push(`local ${svc} = game:GetService("${svc}")`);
    }
  }
  if (services.size > 0) lines.push("");

  // DataStore variable
  if (services.has("DataStoreService")) {
    lines.push(`local dataStore = DataStoreService:GetDataStore("PlayerData")`);
    lines.push("");
  }

  // RemoteEvent declarations
  const remoteNames = new Set<string>();
  for (const n of nodes) {
    if (n.data.nodeType === "fire_remote" || n.data.nodeType === "fire_server" || n.data.nodeType === "screen_shake") {
      const name = n.data.values?.eventName as string || "MyEvent";
      remoteNames.add(name);
    }
  }
  if (allTypes.has("screen_shake")) remoteNames.add("ScreenShake");
  if (remoteNames.size > 0) {
    for (const name of remoteNames) {
      lines.push(`local ${name}Event = ReplicatedStorage:FindFirstChild("${name}") or Instance.new("RemoteEvent")`);
      lines.push(`${name}Event.Name = "${name}"`);
      lines.push(`${name}Event.Parent = ReplicatedStorage`);
    }
    lines.push("");
  }

  // Build adjacency: for each node, find what signal edges connect to it
  const signalEdges = edges.filter((e) => {
    // Signal edges connect signal outputs to signal inputs
    return true; // All edges in our system are signal/data flow
  });

  // For each trigger, generate a handler block
  for (const trigger of triggerNodes) {
    const chain = getSignalChain(trigger.id, nodes, signalEdges);
    lines.push(...generateTriggerBlock(trigger, chain, nodes, edges));
    lines.push("");
  }

  lines.push(`print("${scriptName} loaded")`);
  lines.push("");

  return lines.join("\n");
}

/** Follow signal edges from a trigger through the action chain. */
function getSignalChain(
  startId: string,
  nodes: Node<NodeData>[],
  edges: Edge[],
): Node<NodeData>[] {
  const chain: Node<NodeData>[] = [];
  const visited = new Set<string>();
  let currentId = startId;

  while (currentId) {
    if (visited.has(currentId)) break;
    visited.add(currentId);

    // Find signal edge from current node's signal output
    const outEdge = edges.find(
      (e) =>
        e.source === currentId &&
        (e.sourceHandle === "signal" ||
          e.sourceHandle === "true" ||
          e.sourceHandle === "Then" ||
          !e.sourceHandle),
    );

    if (!outEdge) break;

    const nextNode = nodes.find((n) => n.id === outEdge.target);
    if (!nextNode) break;

    chain.push(nextNode);
    currentId = nextNode.id;
  }

  return chain;
}

/** Get the value for a node input — either from a connected edge or the default. */
function getInputValue(
  nodeId: string,
  inputId: string,
  nodes: Node<NodeData>[],
  edges: Edge[],
): string {
  const node = nodes.find((n) => n.id === nodeId);
  if (!node) return "nil";

  // Check if there's a data edge connecting to this input
  const dataEdge = edges.find(
    (e) => e.target === nodeId && e.targetHandle === inputId,
  );

  if (dataEdge) {
    // Return a variable reference from the source node
    return `_${dataEdge.source}_${dataEdge.sourceHandle}`;
  }

  // Use the node's configured value or the default
  const val = node.data.values?.[inputId];
  if (val !== undefined) {
    if (typeof val === "string") return `"${val}"`;
    return String(val);
  }

  const typeDef = NODE_TYPES[node.data.nodeType];
  const portDef = typeDef?.inputs.find((p) => p.id === inputId);
  if (portDef?.defaultValue !== undefined) {
    if (typeof portDef.defaultValue === "string")
      return `"${portDef.defaultValue}"`;
    return String(portDef.defaultValue);
  }

  return "nil";
}

/** Generate Luau code for a trigger node and its connected action chain. */
function generateTriggerBlock(
  trigger: Node<NodeData>,
  chain: Node<NodeData>[],
  allNodes: Node<NodeData>[],
  allEdges: Edge[],
): string[] {
  const lines: string[] = [];
  const t = trigger.data.nodeType;

  if (t === "on_touched") {
    const tag = getInputValue(trigger.id, "tag", allNodes, allEdges);
    lines.push(`-- On Touched: parts tagged ${tag}`);
    lines.push(`for _, part in CollectionService:GetTagged(${tag}) do`);
    lines.push(`\tpart.Touched:Connect(function(hit)`);
    lines.push(`\t\tlocal player = Players:GetPlayerFromCharacter(hit.Parent)`);
    lines.push(`\t\tif not player then return end`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend)`);
    lines.push(`end`);
  } else if (t === "on_timer") {
    const interval = getInputValue(trigger.id, "interval", allNodes, allEdges);
    lines.push(`-- Timer: every ${interval} seconds`);
    lines.push(`task.spawn(function()`);
    lines.push(`\twhile true do`);
    lines.push(`\t\ttask.wait(${interval})`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend`);
    lines.push(`end)`);
  } else if (t === "on_player_join") {
    lines.push(`-- On Player Join`);
    lines.push(`Players.PlayerAdded:Connect(function(player)`);
    lines.push(...indentChain(chain, allNodes, allEdges, 1));
    lines.push(`end)`);
  } else if (t === "on_died") {
    lines.push(`-- On Player Died`);
    lines.push(`Players.PlayerAdded:Connect(function(player)`);
    lines.push(`\tplayer.CharacterAdded:Connect(function(character)`);
    lines.push(`\t\tlocal humanoid = character:WaitForChild("Humanoid")`);
    lines.push(`\t\thumanoid.Died:Connect(function()`);
    lines.push(...indentChain(chain, allNodes, allEdges, 3));
    lines.push(`\t\tend)`);
    lines.push(`\tend)`);
    lines.push(`end)`);
  } else if (t === "on_player_leave") {
    lines.push(`-- On Player Leave`);
    lines.push(`Players.PlayerRemoving:Connect(function(player)`);
    lines.push(...indentChain(chain, allNodes, allEdges, 1));
    lines.push(`end)`);
  } else if (t === "on_chat") {
    const keyword = getInputValue(trigger.id, "keyword", allNodes, allEdges);
    lines.push(`-- On Chat${keyword !== '""' ? ` (keyword: ${keyword})` : ""}`);
    lines.push(`Players.PlayerAdded:Connect(function(player)`);
    lines.push(`\tplayer.Chatted:Connect(function(message)`);
    if (keyword !== '""') {
      lines.push(`\t\tif not string.find(string.lower(message), string.lower(${keyword})) then return end`);
    }
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend)`);
    lines.push(`end)`);
  } else if (t === "on_value_changed") {
    const valueName = getInputValue(trigger.id, "valueName", allNodes, allEdges);
    lines.push(`-- On Value Changed: ${valueName}`);
    lines.push(`local _valueObj = workspace:FindFirstChild(${valueName}, true)`);
    lines.push(`if _valueObj then`);
    lines.push(`\t_valueObj:GetPropertyChangedSignal("Value"):Connect(function()`);
    lines.push(`\t\tlocal _${trigger.id.replace(/[^a-z0-9]/gi, "_")}_newValue = _valueObj.Value`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend)`);
    lines.push(`end`);
  } else if (t === "on_proximity") {
    const tag = getInputValue(trigger.id, "tag", allNodes, allEdges);
    const radius = getInputValue(trigger.id, "radius", allNodes, allEdges);
    lines.push(`-- On Proximity: parts tagged ${tag} within ${radius} studs`);
    lines.push(`for _, part in CollectionService:GetTagged(${tag}) do`);
    lines.push(`\tlocal prompt = Instance.new("ProximityPrompt")`);
    lines.push(`\tprompt.MaxActivationDistance = ${radius}`);
    lines.push(`\tprompt.HoldDuration = 0`);
    lines.push(`\tprompt.ActionText = "Interact"`);
    lines.push(`\tprompt.Parent = part`);
    lines.push(`\tprompt.Triggered:Connect(function(player)`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend)`);
    lines.push(`end`);
  } else if (t === "on_click") {
    const tag = getInputValue(trigger.id, "tag", allNodes, allEdges);
    lines.push(`-- On Click: parts tagged ${tag}`);
    lines.push(`for _, part in CollectionService:GetTagged(${tag}) do`);
    lines.push(`\tlocal detector = part:FindFirstChildOfClass("ClickDetector") or Instance.new("ClickDetector")`);
    lines.push(`\tdetector.Parent = part`);
    lines.push(`\tdetector.MouseClick:Connect(function(player)`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend)`);
    lines.push(`end`);
  } else if (t === "on_gamepass_purchased") {
    const gamepassId = getInputValue(trigger.id, "gamepassId", allNodes, allEdges);
    lines.push(`-- On GamePass Purchased: ${gamepassId}`);
    lines.push(`MarketplaceService.PromptGamePassPurchaseFinished:Connect(function(player, passId, wasPurchased)`);
    lines.push(`\tif passId == ${gamepassId} and wasPurchased then`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\tend`);
    lines.push(`end)`);
  } else if (t === "on_developer_product") {
    const productId = getInputValue(trigger.id, "productId", allNodes, allEdges);
    lines.push(`-- On Developer Product Purchased: ${productId}`);
    lines.push(`local _existingCallback = MarketplaceService.ProcessReceipt`);
    lines.push(`MarketplaceService.ProcessReceipt = function(receiptInfo)`);
    lines.push(`\tif _existingCallback then`);
    lines.push(`\t\tlocal result = _existingCallback(receiptInfo)`);
    lines.push(`\t\tif result == Enum.ProductPurchaseDecision.PurchaseGranted then return result end`);
    lines.push(`\tend`);
    lines.push(`\tlocal player = Players:GetPlayerByUserId(receiptInfo.PlayerId)`);
    lines.push(`\tif not player then return Enum.ProductPurchaseDecision.NotProcessedYet end`);
    lines.push(`\tif receiptInfo.ProductId == ${productId} then`);
    lines.push(...indentChain(chain, allNodes, allEdges, 2));
    lines.push(`\t\treturn Enum.ProductPurchaseDecision.PurchaseGranted`);
    lines.push(`\tend`);
    lines.push(`\treturn Enum.ProductPurchaseDecision.NotProcessedYet`);
    lines.push(`end`);
  }

  return lines;
}

/** Generate code for a chain of action/logic nodes at a given indent level. */
function indentChain(
  chain: Node<NodeData>[],
  allNodes: Node<NodeData>[],
  allEdges: Edge[],
  indent: number,
): string[] {
  const lines: string[] = [];
  const tabs = "\t".repeat(indent);

  for (const node of chain) {
    const t = node.data.nodeType;

    if (t === "take_damage") {
      const amount = getInputValue(node.id, "amount", allNodes, allEdges);
      lines.push(`${tabs}-- Take Damage`);
      lines.push(`${tabs}local character = player.Character`);
      lines.push(`${tabs}if character then`);
      lines.push(`${tabs}\tlocal humanoid = character:FindFirstChild("Humanoid")`);
      lines.push(`${tabs}\tif humanoid then`);
      lines.push(`${tabs}\t\thumanoid:TakeDamage(${amount})`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
    } else if (t === "move_object") {
      const direction = getInputValue(node.id, "direction", allNodes, allEdges);
      const distance = getInputValue(node.id, "distance", allNodes, allEdges);
      lines.push(`${tabs}-- Move Object`);
      lines.push(`${tabs}local moveDir = Vector3.new(0, ${direction === '"up"' ? distance : "0"}, ${direction === '"forward"' ? distance : "0"})`);
      lines.push(`${tabs}local goal = { CFrame = part.CFrame + moveDir }`);
      lines.push(`${tabs}local tween = TweenService:Create(part, TweenInfo.new(1), goal)`);
      lines.push(`${tabs}tween:Play()`);
    } else if (t === "play_sound") {
      const soundId = getInputValue(node.id, "soundId", allNodes, allEdges);
      lines.push(`${tabs}-- Play Sound`);
      lines.push(`${tabs}local sound = Instance.new("Sound")`);
      lines.push(`${tabs}sound.SoundId = ${soundId}`);
      lines.push(`${tabs}sound.Parent = workspace`);
      lines.push(`${tabs}sound:Play()`);
      lines.push(`${tabs}sound.Ended:Once(function() sound:Destroy() end)`);
    } else if (t === "print_message") {
      const message = getInputValue(node.id, "message", allNodes, allEdges);
      lines.push(`${tabs}print(${message})`);
    } else if (t === "heal_player") {
      const amount = getInputValue(node.id, "amount", allNodes, allEdges);
      lines.push(`${tabs}-- Heal Player`);
      lines.push(`${tabs}local character = player and player.Character`);
      lines.push(`${tabs}if character then`);
      lines.push(`${tabs}\tlocal humanoid = character:FindFirstChild("Humanoid")`);
      lines.push(`${tabs}\tif humanoid then`);
      lines.push(`${tabs}\t\thumanoid.Health = math.min(humanoid.Health + ${amount}, humanoid.MaxHealth)`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
    } else if (t === "kill_player") {
      lines.push(`${tabs}-- Kill Player`);
      lines.push(`${tabs}local character = player and player.Character`);
      lines.push(`${tabs}if character then`);
      lines.push(`${tabs}\tlocal humanoid = character:FindFirstChild("Humanoid")`);
      lines.push(`${tabs}\tif humanoid then humanoid.Health = 0 end`);
      lines.push(`${tabs}end`);
    } else if (t === "respawn_player") {
      lines.push(`${tabs}-- Respawn Player`);
      lines.push(`${tabs}if player then player:LoadCharacter() end`);
    } else if (t === "teleport_player") {
      const x = getInputValue(node.id, "x", allNodes, allEdges);
      const y = getInputValue(node.id, "y", allNodes, allEdges);
      const z = getInputValue(node.id, "z", allNodes, allEdges);
      lines.push(`${tabs}-- Teleport Player`);
      lines.push(`${tabs}local character = player and player.Character`);
      lines.push(`${tabs}if character then`);
      lines.push(`${tabs}\tcharacter:PivotTo(CFrame.new(${x}, ${y}, ${z}))`);
      lines.push(`${tabs}end`);
    } else if (t === "set_part_color") {
      const tag = getInputValue(node.id, "tag", allNodes, allEdges);
      const color = getInputValue(node.id, "color", allNodes, allEdges);
      lines.push(`${tabs}-- Set Part Color`);
      lines.push(`${tabs}for _, colorPart in CollectionService:GetTagged(${tag}) do`);
      lines.push(`${tabs}\tcolorPart.BrickColor = BrickColor.new(${color})`);
      lines.push(`${tabs}end`);
    } else if (t === "show_hint") {
      const message = getInputValue(node.id, "message", allNodes, allEdges);
      const duration = getInputValue(node.id, "duration", allNodes, allEdges);
      lines.push(`${tabs}-- Show Hint`);
      lines.push(`${tabs}local hint = Instance.new("Hint")`);
      lines.push(`${tabs}hint.Text = ${message}`);
      lines.push(`${tabs}hint.Parent = workspace`);
      lines.push(`${tabs}task.delay(${duration}, function() hint:Destroy() end)`);
    } else if (t === "give_points") {
      const amount = getInputValue(node.id, "amount", allNodes, allEdges);
      const stat = getInputValue(node.id, "stat", allNodes, allEdges);
      lines.push(`${tabs}-- Give Points`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal leaderstats = player:FindFirstChild("leaderstats")`);
      lines.push(`${tabs}\tif leaderstats then`);
      lines.push(`${tabs}\t\tlocal statValue = leaderstats:FindFirstChild(${stat})`);
      lines.push(`${tabs}\t\tif statValue then statValue.Value += ${amount} end`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
    } else if (t === "wait_delay") {
      const seconds = getInputValue(node.id, "seconds", allNodes, allEdges);
      lines.push(`${tabs}task.wait(${seconds})`);
    } else if (t === "random_number") {
      const min = getInputValue(node.id, "min", allNodes, allEdges);
      const max = getInputValue(node.id, "max", allNodes, allEdges);
      const varName = `_${node.id.replace(/[^a-z0-9]/gi, "_")}_value`;
      lines.push(`${tabs}-- Random Number`);
      lines.push(`${tabs}local ${varName} = math.random(${min}, ${max})`);
    } else if (t === "compare") {
      const a = getInputValue(node.id, "a", allNodes, allEdges);
      const op = getInputValue(node.id, "operator", allNodes, allEdges);
      const b = getInputValue(node.id, "b", allNodes, allEdges);
      // Find true/false branches
      const trueBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "true",
      );
      const falseBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "false",
      );
      lines.push(`${tabs}-- Compare`);
      lines.push(`${tabs}if ${a} ${op.replace(/^"|"$/g, "")} ${b} then`);
      if (trueBranch) {
        const trueNode = allNodes.find((n) => n.id === trueBranch.target);
        if (trueNode) {
          lines.push(...indentChain([trueNode], allNodes, allEdges, indent + 1));
        }
      }
      if (falseBranch) {
        lines.push(`${tabs}else`);
        const falseNode = allNodes.find((n) => n.id === falseBranch.target);
        if (falseNode) {
          lines.push(...indentChain([falseNode], allNodes, allEdges, indent + 1));
        }
      }
      lines.push(`${tabs}end`);
    } else if (t === "if_else") {
      const condition = getInputValue(node.id, "condition", allNodes, allEdges);
      const trueBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "true",
      );
      const falseBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "false",
      );
      lines.push(`${tabs}if ${condition} then`);
      if (trueBranch) {
        const trueNode = allNodes.find((n) => n.id === trueBranch.target);
        if (trueNode) {
          lines.push(...indentChain([trueNode], allNodes, allEdges, indent + 1));
        }
      }
      if (falseBranch) {
        lines.push(`${tabs}else`);
        const falseNode = allNodes.find((n) => n.id === falseBranch.target);
        if (falseNode) {
          lines.push(...indentChain([falseNode], allNodes, allEdges, indent + 1));
        }
      }
      lines.push(`${tabs}end`);

    // ── Data & Persistence ──
    } else if (t === "save_data") {
      const key = getInputValue(node.id, "key", allNodes, allEdges);
      const value = getInputValue(node.id, "value", allNodes, allEdges);
      lines.push(`${tabs}-- Save Data`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal saveKey = player.UserId .. "_" .. ${key}`);
      lines.push(`${tabs}\tlocal ok, err = pcall(function()`);
      lines.push(`${tabs}\t\tdataStore:SetAsync(saveKey, ${value})`);
      lines.push(`${tabs}\tend)`);
      lines.push(`${tabs}\tif not ok then warn("Save failed:", err) end`);
      lines.push(`${tabs}end`);
    } else if (t === "load_data") {
      const key = getInputValue(node.id, "key", allNodes, allEdges);
      const varName = `_${node.id.replace(/[^a-z0-9]/gi, "_")}_value`;
      lines.push(`${tabs}-- Load Data`);
      lines.push(`${tabs}local ${varName} = 0`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal loadKey = player.UserId .. "_" .. ${key}`);
      lines.push(`${tabs}\tlocal ok, result = pcall(function()`);
      lines.push(`${tabs}\t\treturn dataStore:GetAsync(loadKey)`);
      lines.push(`${tabs}\tend)`);
      lines.push(`${tabs}\tif ok and result ~= nil then ${varName} = result end`);
      lines.push(`${tabs}end`);
    } else if (t === "set_leaderstat") {
      const stat = getInputValue(node.id, "stat", allNodes, allEdges);
      const value = getInputValue(node.id, "value", allNodes, allEdges);
      lines.push(`${tabs}-- Set Leaderstat`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal leaderstats = player:FindFirstChild("leaderstats")`);
      lines.push(`${tabs}\tif not leaderstats then`);
      lines.push(`${tabs}\t\tleaderstats = Instance.new("Folder")`);
      lines.push(`${tabs}\t\tleaderstats.Name = "leaderstats"`);
      lines.push(`${tabs}\t\tleaderstats.Parent = player`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}\tlocal statObj = leaderstats:FindFirstChild(${stat})`);
      lines.push(`${tabs}\tif not statObj then`);
      lines.push(`${tabs}\t\tstatObj = Instance.new("IntValue")`);
      lines.push(`${tabs}\t\tstatObj.Name = ${stat}`);
      lines.push(`${tabs}\t\tstatObj.Parent = leaderstats`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}\tstatObj.Value = ${value}`);
      lines.push(`${tabs}end`);
    } else if (t === "get_leaderstat") {
      const stat = getInputValue(node.id, "stat", allNodes, allEdges);
      const varName = `_${node.id.replace(/[^a-z0-9]/gi, "_")}_value`;
      lines.push(`${tabs}-- Get Leaderstat`);
      lines.push(`${tabs}local ${varName} = 0`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal leaderstats = player:FindFirstChild("leaderstats")`);
      lines.push(`${tabs}\tif leaderstats then`);
      lines.push(`${tabs}\t\tlocal statObj = leaderstats:FindFirstChild(${stat})`);
      lines.push(`${tabs}\t\tif statObj then ${varName} = statObj.Value end`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);

    // ── UI & Feedback ──
    } else if (t === "show_notification") {
      const title = getInputValue(node.id, "title", allNodes, allEdges);
      const text = getInputValue(node.id, "text", allNodes, allEdges);
      const duration = getInputValue(node.id, "duration", allNodes, allEdges);
      lines.push(`${tabs}-- Show Notification`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal starterGui = player:FindFirstChildOfClass("PlayerGui")`);
      lines.push(`${tabs}\tif starterGui then`);
      lines.push(`${tabs}\t\tgame:GetService("StarterGui"):SetCore("SendNotification", {`);
      lines.push(`${tabs}\t\t\tTitle = ${title},`);
      lines.push(`${tabs}\t\t\tText = ${text},`);
      lines.push(`${tabs}\t\t\tDuration = ${duration},`);
      lines.push(`${tabs}\t\t})`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
    } else if (t === "screen_shake") {
      const intensity = getInputValue(node.id, "intensity", allNodes, allEdges);
      const duration = getInputValue(node.id, "duration", allNodes, allEdges);
      lines.push(`${tabs}-- Screen Shake`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tScreenShakeEvent:FireClient(player, ${intensity}, ${duration})`);
      lines.push(`${tabs}end`);
    } else if (t === "create_particle") {
      const tag = getInputValue(node.id, "tag", allNodes, allEdges);
      const color = getInputValue(node.id, "color", allNodes, allEdges);
      const duration = getInputValue(node.id, "duration", allNodes, allEdges);
      lines.push(`${tabs}-- Create Particle Effect`);
      lines.push(`${tabs}for _, effectPart in CollectionService:GetTagged(${tag}) do`);
      lines.push(`${tabs}\tlocal emitter = Instance.new("ParticleEmitter")`);
      lines.push(`${tabs}\temitter.Color = ColorSequence.new(BrickColor.new(${color}).Color)`);
      lines.push(`${tabs}\temitter.Lifetime = NumberRange.new(0.5, 1.5)`);
      lines.push(`${tabs}\temitter.Rate = 50`);
      lines.push(`${tabs}\temitter.Parent = effectPart`);
      lines.push(`${tabs}\ttask.delay(${duration}, function() emitter:Destroy() end)`);
      lines.push(`${tabs}end`);
    } else if (t === "change_lighting") {
      const brightness = getInputValue(node.id, "brightness", allNodes, allEdges);
      const clockTime = getInputValue(node.id, "clockTime", allNodes, allEdges);
      const fogEnd = getInputValue(node.id, "fogEnd", allNodes, allEdges);
      lines.push(`${tabs}-- Change Lighting`);
      lines.push(`${tabs}Lighting.Brightness = ${brightness}`);
      lines.push(`${tabs}Lighting.ClockTime = ${clockTime}`);
      lines.push(`${tabs}Lighting.FogEnd = ${fogEnd}`);

    // ── Movement & Physics ──
    } else if (t === "apply_force") {
      const fx = getInputValue(node.id, "forceX", allNodes, allEdges);
      const fy = getInputValue(node.id, "forceY", allNodes, allEdges);
      const fz = getInputValue(node.id, "forceZ", allNodes, allEdges);
      lines.push(`${tabs}-- Apply Force`);
      lines.push(`${tabs}if part then`);
      lines.push(`${tabs}\tpart.Anchored = false`);
      lines.push(`${tabs}\tlocal force = Instance.new("VectorForce")`);
      lines.push(`${tabs}\tlocal att = part:FindFirstChildOfClass("Attachment") or Instance.new("Attachment")`);
      lines.push(`${tabs}\tatt.Parent = part`);
      lines.push(`${tabs}\tforce.Attachment0 = att`);
      lines.push(`${tabs}\tforce.Force = Vector3.new(${fx}, ${fy}, ${fz})`);
      lines.push(`${tabs}\tforce.RelativeTo = Enum.ActuatorRelativeTo.World`);
      lines.push(`${tabs}\tforce.Parent = part`);
      lines.push(`${tabs}\ttask.delay(0.1, function() force:Destroy() end)`);
      lines.push(`${tabs}end`);
    } else if (t === "tween_property") {
      const property = getInputValue(node.id, "property", allNodes, allEdges);
      const targetValue = getInputValue(node.id, "targetValue", allNodes, allEdges);
      const duration = getInputValue(node.id, "duration", allNodes, allEdges);
      lines.push(`${tabs}-- Tween Property`);
      lines.push(`${tabs}if part then`);
      lines.push(`${tabs}\tlocal goal = { [${property}] = ${targetValue} }`);
      lines.push(`${tabs}\tlocal tween = TweenService:Create(part, TweenInfo.new(${duration}), goal)`);
      lines.push(`${tabs}\ttween:Play()`);
      lines.push(`${tabs}end`);
    } else if (t === "anchor_toggle") {
      const anchored = getInputValue(node.id, "anchored", allNodes, allEdges);
      lines.push(`${tabs}-- Set Anchored`);
      lines.push(`${tabs}if part then part.Anchored = ${anchored} end`);
    } else if (t === "destroy_part") {
      lines.push(`${tabs}-- Destroy Part`);
      lines.push(`${tabs}if part then part:Destroy() end`);
    } else if (t === "clone_part") {
      const varName = `_${node.id.replace(/[^a-z0-9]/gi, "_")}_clone`;
      lines.push(`${tabs}-- Clone Part`);
      lines.push(`${tabs}local ${varName} = nil`);
      lines.push(`${tabs}if part then`);
      lines.push(`${tabs}\t${varName} = part:Clone()`);
      lines.push(`${tabs}\t${varName}.Parent = workspace`);
      lines.push(`${tabs}end`);

    // ── Economy & Monetization ──
    } else if (t === "give_currency") {
      const currency = getInputValue(node.id, "currency", allNodes, allEdges);
      const amount = getInputValue(node.id, "amount", allNodes, allEdges);
      lines.push(`${tabs}-- Give Currency`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal leaderstats = player:FindFirstChild("leaderstats")`);
      lines.push(`${tabs}\tif leaderstats then`);
      lines.push(`${tabs}\t\tlocal curr = leaderstats:FindFirstChild(${currency})`);
      lines.push(`${tabs}\t\tif curr then curr.Value += ${amount} end`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
    } else if (t === "spend_currency") {
      const currency = getInputValue(node.id, "currency", allNodes, allEdges);
      const amount = getInputValue(node.id, "amount", allNodes, allEdges);
      const successBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "success",
      );
      const failBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "fail",
      );
      lines.push(`${tabs}-- Spend Currency`);
      lines.push(`${tabs}local _canAfford = false`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal leaderstats = player:FindFirstChild("leaderstats")`);
      lines.push(`${tabs}\tif leaderstats then`);
      lines.push(`${tabs}\t\tlocal curr = leaderstats:FindFirstChild(${currency})`);
      lines.push(`${tabs}\t\tif curr and curr.Value >= ${amount} then`);
      lines.push(`${tabs}\t\t\tcurr.Value -= ${amount}`);
      lines.push(`${tabs}\t\t\t_canAfford = true`);
      lines.push(`${tabs}\t\tend`);
      lines.push(`${tabs}\tend`);
      lines.push(`${tabs}end`);
      lines.push(`${tabs}if _canAfford then`);
      if (successBranch) {
        const successNode = allNodes.find((n) => n.id === successBranch.target);
        if (successNode) {
          lines.push(...indentChain([successNode], allNodes, allEdges, indent + 1));
        }
      }
      if (failBranch) {
        lines.push(`${tabs}else`);
        const failNode = allNodes.find((n) => n.id === failBranch.target);
        if (failNode) {
          lines.push(...indentChain([failNode], allNodes, allEdges, indent + 1));
        }
      }
      lines.push(`${tabs}end`);
    } else if (t === "prompt_purchase") {
      const assetId = getInputValue(node.id, "assetId", allNodes, allEdges);
      lines.push(`${tabs}-- Prompt Purchase`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tMarketplaceService:PromptPurchase(player, ${assetId})`);
      lines.push(`${tabs}end`);
    } else if (t === "prompt_gamepass") {
      const gamepassId = getInputValue(node.id, "gamepassId", allNodes, allEdges);
      lines.push(`${tabs}-- Prompt GamePass Purchase`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tMarketplaceService:PromptGamePassPurchase(player, ${gamepassId})`);
      lines.push(`${tabs}end`);
    } else if (t === "check_gamepass") {
      const gamepassId = getInputValue(node.id, "gamepassId", allNodes, allEdges);
      const ownsBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "owns",
      );
      const doesNotOwnBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "doesNotOwn",
      );
      lines.push(`${tabs}-- Check GamePass`);
      lines.push(`${tabs}local _ownsPass = false`);
      lines.push(`${tabs}if player then`);
      lines.push(`${tabs}\tlocal ok, result = pcall(function()`);
      lines.push(`${tabs}\t\treturn MarketplaceService:UserOwnsGamePassAsync(player.UserId, ${gamepassId})`);
      lines.push(`${tabs}\tend)`);
      lines.push(`${tabs}\t_ownsPass = ok and result`);
      lines.push(`${tabs}end`);
      lines.push(`${tabs}if _ownsPass then`);
      if (ownsBranch) {
        const ownsNode = allNodes.find((n) => n.id === ownsBranch.target);
        if (ownsNode) {
          lines.push(...indentChain([ownsNode], allNodes, allEdges, indent + 1));
        }
      }
      if (doesNotOwnBranch) {
        lines.push(`${tabs}else`);
        const noNode = allNodes.find((n) => n.id === doesNotOwnBranch.target);
        if (noNode) {
          lines.push(...indentChain([noNode], allNodes, allEdges, indent + 1));
        }
      }
      lines.push(`${tabs}end`);

    // ── Communication ──
    } else if (t === "fire_remote") {
      const eventName = getInputValue(node.id, "eventName", allNodes, allEdges);
      const target = getInputValue(node.id, "target", allNodes, allEdges);
      const evtVar = `${eventName.replace(/^"|"$/g, "")}Event`;
      lines.push(`${tabs}-- Fire Remote Event`);
      lines.push(`${tabs}if ${target} == "all" then`);
      lines.push(`${tabs}\t${evtVar}:FireAllClients()`);
      lines.push(`${tabs}elseif player then`);
      lines.push(`${tabs}\t${evtVar}:FireClient(player)`);
      lines.push(`${tabs}end`);
    } else if (t === "fire_server") {
      const eventName = getInputValue(node.id, "eventName", allNodes, allEdges);
      const evtVar = `${eventName.replace(/^"|"$/g, "")}Event`;
      lines.push(`${tabs}-- Fire Server Event`);
      lines.push(`${tabs}${evtVar}:FireServer()`);

    // ── New Logic ──
    } else if (t === "for_each_player") {
      const bodyBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "body",
      );
      const doneBranch = allEdges.find(
        (e) => e.source === node.id && e.sourceHandle === "done",
      );
      lines.push(`${tabs}-- For Each Player`);
      lines.push(`${tabs}for _, player in Players:GetPlayers() do`);
      if (bodyBranch) {
        const bodyNode = allNodes.find((n) => n.id === bodyBranch.target);
        if (bodyNode) {
          lines.push(...indentChain([bodyNode], allNodes, allEdges, indent + 1));
        }
      }
      lines.push(`${tabs}end`);
      if (doneBranch) {
        const doneNode = allNodes.find((n) => n.id === doneBranch.target);
        if (doneNode) {
          lines.push(...indentChain([doneNode], allNodes, allEdges, indent));
        }
      }
    } else if (t === "math_operation") {
      const a = getInputValue(node.id, "a", allNodes, allEdges);
      const op = getInputValue(node.id, "operator", allNodes, allEdges);
      const b = getInputValue(node.id, "b", allNodes, allEdges);
      const varName = `_${node.id.replace(/[^a-z0-9]/gi, "_")}_result`;
      const cleanOp = op.replace(/^"|"$/g, "");
      lines.push(`${tabs}-- Math Operation`);
      lines.push(`${tabs}local ${varName} = ${a} ${cleanOp} ${b}`);
    } else if (t === "string_format") {
      const a = getInputValue(node.id, "a", allNodes, allEdges);
      const b = getInputValue(node.id, "b", allNodes, allEdges);
      const varName = `_${node.id.replace(/[^a-z0-9]/gi, "_")}_result`;
      lines.push(`${tabs}-- Join Text`);
      lines.push(`${tabs}local ${varName} = tostring(${a}) .. tostring(${b})`);
    } else if (t === "and_gate" || t === "or_gate") {
      // Pure data nodes — values resolved by getInputValue when referenced
      const a = getInputValue(node.id, "a", allNodes, allEdges);
      const b = getInputValue(node.id, "b", allNodes, allEdges);
      const varName = `_${node.id.replace(/[^a-z0-9]/gi, "_")}_result`;
      const op = t === "and_gate" ? "and" : "or";
      lines.push(`${tabs}local ${varName} = ${a} ${op} ${b}`);
    }
  }

  return lines;
}
