/**
 * Monetization system — GamePasses, Developer Products, and currency configuration.
 * Generates Luau server scripts for handling purchases and economy.
 */

export interface GamePassDefinition {
  id: number;
  name: string;
  price: number;
  description: string;
  benefits: string[];
}

export interface DevProductDefinition {
  id: number;
  name: string;
  price: number;
  description: string;
  action: "give_coins" | "double_xp" | "extra_life" | "speed_boost" | "custom";
  actionValue: number;
}

export interface CurrencyConfig {
  name: string;
  startingAmount: number;
  icon: string;
}

export interface MonetizationConfig {
  gamePasses: GamePassDefinition[];
  devProducts: DevProductDefinition[];
  currencies: CurrencyConfig[];
}

export function getDefaultMonetizationConfig(template: string): MonetizationConfig {
  const base: MonetizationConfig = {
    gamePasses: [],
    devProducts: [],
    currencies: [{ name: "Coins", startingAmount: 0, icon: "coin" }],
  };

  switch (template) {
    case "obby":
      base.gamePasses = [
        { id: 0, name: "Skip Stage", price: 75, description: "Skip any stage you're stuck on", benefits: ["Skip button on each stage"] },
        { id: 0, name: "Double Speed", price: 150, description: "Walk 2x faster permanently", benefits: ["2x WalkSpeed"] },
        { id: 0, name: "VIP", price: 350, description: "Exclusive trail + VIP badge", benefits: ["Rainbow trail", "VIP chat tag"] },
      ];
      base.devProducts = [
        { id: 0, name: "25 Coins", price: 25, description: "Get 25 coins instantly", action: "give_coins", actionValue: 25 },
        { id: 0, name: "Extra Life", price: 10, description: "Respawn without losing progress", action: "extra_life", actionValue: 1 },
      ];
      break;
    case "tycoon":
      base.currencies = [
        { name: "Cash", startingAmount: 100, icon: "dollar" },
        { name: "Gems", startingAmount: 0, icon: "gem" },
      ];
      base.gamePasses = [
        { id: 0, name: "2x Income", price: 199, description: "Earn double from all sources", benefits: ["2x cash multiplier"] },
        { id: 0, name: "Auto Collect", price: 149, description: "Automatically collect drops", benefits: ["Auto-collect items"] },
        { id: 0, name: "VIP", price: 499, description: "Exclusive tycoon perks", benefits: ["VIP area", "Bonus starter cash"] },
      ];
      base.devProducts = [
        { id: 0, name: "1000 Cash", price: 49, description: "Instant cash boost", action: "give_coins", actionValue: 1000 },
        { id: 0, name: "Speed Boost", price: 25, description: "5 minutes of 2x speed", action: "speed_boost", actionValue: 300 },
      ];
      break;
    case "simulator":
      base.currencies = [
        { name: "Coins", startingAmount: 0, icon: "coin" },
        { name: "Gems", startingAmount: 0, icon: "gem" },
      ];
      base.gamePasses = [
        { id: 0, name: "2x Clicks", price: 149, description: "Double click power", benefits: ["2x click value"] },
        { id: 0, name: "Auto Click", price: 249, description: "Automatic clicking", benefits: ["1 click/second auto"] },
        { id: 0, name: "Lucky Eggs", price: 399, description: "2x pet hatch luck", benefits: ["Double legendary chance"] },
      ];
      base.devProducts = [
        { id: 0, name: "500 Gems", price: 49, description: "Premium gems", action: "give_coins", actionValue: 500 },
      ];
      break;
    case "rpg":
      base.currencies = [
        { name: "Gold", startingAmount: 50, icon: "coin" },
        { name: "Crystals", startingAmount: 0, icon: "gem" },
      ];
      base.gamePasses = [
        { id: 0, name: "2x XP", price: 199, description: "Level up twice as fast", benefits: ["Double XP gain"] },
        { id: 0, name: "Extra Inventory", price: 149, description: "Double your bag space", benefits: ["2x inventory slots"] },
      ];
      base.devProducts = [
        { id: 0, name: "100 Gold", price: 49, description: "Quick gold", action: "give_coins", actionValue: 100 },
      ];
      break;
    default:
      base.gamePasses = [
        { id: 0, name: "VIP", price: 199, description: "VIP benefits", benefits: ["VIP badge", "Special perks"] },
      ];
      base.devProducts = [
        { id: 0, name: "100 Coins", price: 49, description: "Get coins", action: "give_coins", actionValue: 100 },
      ];
  }

  return base;
}

export function generateMonetizationScript(config: MonetizationConfig): string {
  const lines: string[] = [
    "-- MonetizationHandler: auto-generated by RobloxForge",
    "-- Handles GamePasses, Developer Products, and currency management",
    "",
    'local Players = game:GetService("Players")',
    'local MarketplaceService = game:GetService("MarketplaceService")',
    'local DataStoreService = game:GetService("DataStoreService")',
    "",
    'local currencyStore = DataStoreService:GetDataStore("CurrencyData")',
    "",
  ];

  // GamePass IDs
  lines.push("-- GamePass IDs (replace 0 with real IDs from Creator Hub)");
  lines.push("local GAMEPASSES = {");
  for (const gp of config.gamePasses) {
    lines.push(`\t{ id = ${gp.id}, name = "${gp.name}" },`);
  }
  lines.push("}");
  lines.push("");

  // Dev Product IDs
  lines.push("-- Developer Product IDs (replace 0 with real IDs from Creator Hub)");
  lines.push("local DEV_PRODUCTS = {");
  for (const dp of config.devProducts) {
    lines.push(`\t[${dp.id}] = { name = "${dp.name}", action = "${dp.action}", value = ${dp.actionValue} },`);
  }
  lines.push("}");
  lines.push("");

  // Currency setup
  lines.push("-- Currency configuration");
  lines.push("local CURRENCIES = {");
  for (const c of config.currencies) {
    lines.push(`\t{ name = "${c.name}", startAmount = ${c.startingAmount} },`);
  }
  lines.push("}");
  lines.push("");

  // Player setup function
  lines.push("-- Set up leaderstats and load saved data for each player");
  lines.push("local function setupPlayer(player)");
  lines.push('\tlocal leaderstats = Instance.new("Folder")');
  lines.push('\tleaderstats.Name = "leaderstats"');
  lines.push("\tleaderstats.Parent = player");
  lines.push("");
  lines.push("\tfor _, currency in CURRENCIES do");
  lines.push('\t\tlocal val = Instance.new("IntValue")');
  lines.push("\t\tval.Name = currency.name");
  lines.push("\t\tval.Value = currency.startAmount");
  lines.push("\t\tval.Parent = leaderstats");
  lines.push("");
  lines.push("\t\t-- Load saved data");
  lines.push('\t\tlocal key = player.UserId .. "_" .. currency.name');
  lines.push("\t\tlocal ok, saved = pcall(function()");
  lines.push("\t\t\treturn currencyStore:GetAsync(key)");
  lines.push("\t\tend)");
  lines.push("\t\tif ok and saved then val.Value = saved end");
  lines.push("\tend");
  lines.push("");

  // Check owned GamePasses on join
  lines.push("\t-- Check owned GamePasses");
  lines.push("\tfor _, pass in GAMEPASSES do");
  lines.push("\t\tlocal ok, owns = pcall(function()");
  lines.push("\t\t\treturn MarketplaceService:UserOwnsGamePassAsync(player.UserId, pass.id)");
  lines.push("\t\tend)");
  lines.push("\t\tif ok and owns then");
  lines.push('\t\t\t-- Apply GamePass benefits (customize per pass)');
  lines.push('\t\t\tprint(player.Name .. " owns " .. pass.name)');
  lines.push("\t\tend");
  lines.push("\tend");
  lines.push("end");
  lines.push("");

  // Save on leave
  lines.push("-- Save currency data when player leaves");
  lines.push("local function savePlayer(player)");
  lines.push('\tlocal leaderstats = player:FindFirstChild("leaderstats")');
  lines.push("\tif not leaderstats then return end");
  lines.push("");
  lines.push("\tfor _, currency in CURRENCIES do");
  lines.push("\t\tlocal val = leaderstats:FindFirstChild(currency.name)");
  lines.push("\t\tif val then");
  lines.push('\t\t\tlocal key = player.UserId .. "_" .. currency.name');
  lines.push("\t\t\tpcall(function()");
  lines.push("\t\t\t\tcurrencyStore:SetAsync(key, val.Value)");
  lines.push("\t\t\tend)");
  lines.push("\t\tend");
  lines.push("\tend");
  lines.push("end");
  lines.push("");

  // Process Receipt
  lines.push("-- Handle Developer Product purchases");
  lines.push("MarketplaceService.ProcessReceipt = function(receiptInfo)");
  lines.push("\tlocal player = Players:GetPlayerByUserId(receiptInfo.PlayerId)");
  lines.push("\tif not player then return Enum.ProductPurchaseDecision.NotProcessedYet end");
  lines.push("");
  lines.push("\tlocal product = DEV_PRODUCTS[receiptInfo.ProductId]");
  lines.push("\tif not product then return Enum.ProductPurchaseDecision.NotProcessedYet end");
  lines.push("");
  lines.push('\tif product.action == "give_coins" then');
  lines.push('\t\tlocal leaderstats = player:FindFirstChild("leaderstats")');
  lines.push("\t\tif leaderstats then");
  lines.push('\t\t\tlocal coins = leaderstats:FindFirstChild(CURRENCIES[1] and CURRENCIES[1].name or "Coins")');
  lines.push("\t\t\tif coins then coins.Value += product.value end");
  lines.push("\t\tend");
  lines.push('\telseif product.action == "speed_boost" then');
  lines.push("\t\tlocal character = player.Character");
  lines.push('\t\tif character then');
  lines.push('\t\t\tlocal humanoid = character:FindFirstChild("Humanoid")');
  lines.push("\t\t\tif humanoid then");
  lines.push("\t\t\t\tlocal baseSpeed = humanoid.WalkSpeed");
  lines.push("\t\t\t\thumanoid.WalkSpeed = baseSpeed * 2");
  lines.push("\t\t\t\ttask.delay(product.value, function()");
  lines.push("\t\t\t\t\tif humanoid then humanoid.WalkSpeed = baseSpeed end");
  lines.push("\t\t\t\tend)");
  lines.push("\t\t\tend");
  lines.push("\t\tend");
  lines.push("\tend");
  lines.push("");
  lines.push("\treturn Enum.ProductPurchaseDecision.PurchaseGranted");
  lines.push("end");
  lines.push("");

  // GamePass purchase handler
  lines.push("-- Handle GamePass purchases");
  lines.push("MarketplaceService.PromptGamePassPurchaseFinished:Connect(function(player, passId, wasPurchased)");
  lines.push("\tif not wasPurchased then return end");
  lines.push('\tprint(player.Name .. " purchased GamePass " .. passId)');
  lines.push("\t-- Apply benefits immediately (customize per pass)");
  lines.push("end)");
  lines.push("");

  // Connect events
  lines.push("Players.PlayerAdded:Connect(setupPlayer)");
  lines.push("Players.PlayerRemoving:Connect(savePlayer)");
  lines.push("");
  lines.push('print("MonetizationHandler loaded")');
  lines.push("");

  return lines.join("\n");
}
