import type { MarketRadarSnapshot } from "./marketRadar";

export const EXAMPLE_MARKET_RADAR_SNAPSHOT = {
  schemaVersion: "1.0.0",
  snapshotKind: "public_aggregate",
  observedAt: "2026-07-14T00:00:00.000Z",
  expiresAt: "2026-07-15T00:00:00.000Z",
  researchBasis: {
    experienceCount: 30,
    archetypeCount: 13,
    scope: "public_metadata_aggregate",
  },
  entries: [
    {
      archetype: "one_input_incremental",
      momentum: "high",
      liveOpsCadence: "continuous",
      socialOrientation: "solo_first",
      monetizationDesignCompatibility: {
        category: "optional_convenience",
        strength: "strong",
        rationaleToken: "short_loop_optional_convenience",
      },
      evidenceStrength: "high",
    },
    {
      archetype: "life_roleplay_toybox",
      momentum: "very_high",
      liveOpsCadence: "weekly",
      socialOrientation: "social_sandbox",
      monetizationDesignCompatibility: {
        category: "cosmetic_expression",
        strength: "strong",
        rationaleToken: "identity_cosmetic_expression",
      },
      evidenceStrength: "high",
    },
    {
      archetype: "pet_collection_economy",
      momentum: "high",
      liveOpsCadence: "event_driven",
      socialOrientation: "mixed",
      monetizationDesignCompatibility: {
        category: "seasonal_collection",
        strength: "strong",
        rationaleToken: "bounded_seasonal_collection",
      },
      evidenceStrength: "high",
    },
    {
      archetype: "scarcity_social_risk_tycoon",
      momentum: "high",
      liveOpsCadence: "continuous",
      socialOrientation: "competitive",
      monetizationDesignCompatibility: {
        category: "optional_convenience",
        strength: "moderate",
        rationaleToken: "fair_optional_convenience",
      },
      evidenceStrength: "medium",
    },
    {
      archetype: "cooperative_survival_expedition",
      momentum: "high",
      liveOpsCadence: "event_driven",
      socialOrientation: "cooperative",
      monetizationDesignCompatibility: {
        category: "private_server",
        strength: "strong",
        rationaleToken: "group_private_space",
      },
      evidenceStrength: "high",
    },
    {
      archetype: "asymmetric_round_survival",
      momentum: "medium",
      liveOpsCadence: "seasonal",
      socialOrientation: "competitive",
      monetizationDesignCompatibility: {
        category: "cosmetic_expression",
        strength: "moderate",
        rationaleToken: "role_cosmetic_expression",
      },
      evidenceStrength: "medium",
    },
    {
      archetype: "arena_combat",
      momentum: "high",
      liveOpsCadence: "weekly",
      socialOrientation: "competitive",
      monetizationDesignCompatibility: {
        category: "cosmetic_expression",
        strength: "strong",
        rationaleToken: "fair_combat_cosmetics",
      },
      evidenceStrength: "high",
    },
    {
      archetype: "action_rpg",
      momentum: "medium",
      liveOpsCadence: "seasonal",
      socialOrientation: "mixed",
      monetizationDesignCompatibility: {
        category: "seasonal_collection",
        strength: "moderate",
        rationaleToken: "long_term_themed_collection",
      },
      evidenceStrength: "medium",
    },
    {
      archetype: "fishing_collection",
      momentum: "medium",
      liveOpsCadence: "event_driven",
      socialOrientation: "solo_first",
      monetizationDesignCompatibility: {
        category: "seasonal_collection",
        strength: "strong",
        rationaleToken: "rotating_collection_goals",
      },
      evidenceStrength: "medium",
    },
    {
      archetype: "fashion_avatar_expression",
      momentum: "high",
      liveOpsCadence: "weekly",
      socialOrientation: "social_sandbox",
      monetizationDesignCompatibility: {
        category: "cosmetic_expression",
        strength: "strong",
        rationaleToken: "identity_cosmetic_expression",
      },
      evidenceStrength: "high",
    },
    {
      archetype: "social_performance_sandbox",
      momentum: "medium",
      liveOpsCadence: "event_driven",
      socialOrientation: "social_sandbox",
      monetizationDesignCompatibility: {
        category: "private_server",
        strength: "moderate",
        rationaleToken: "hosted_social_private_space",
      },
      evidenceStrength: "medium",
    },
    {
      archetype: "roster_strategy",
      momentum: "medium",
      liveOpsCadence: "seasonal",
      socialOrientation: "mixed",
      monetizationDesignCompatibility: {
        category: "seasonal_collection",
        strength: "limited",
        rationaleToken: "fair_strategy_collection",
      },
      evidenceStrength: "low",
    },
    {
      archetype: "hide_and_seek",
      momentum: "medium",
      liveOpsCadence: "low_frequency",
      socialOrientation: "competitive",
      monetizationDesignCompatibility: {
        category: "private_server",
        strength: "moderate",
        rationaleToken: "group_private_space",
      },
      evidenceStrength: "medium",
    },
  ],
} as const satisfies MarketRadarSnapshot;
